#' Example Multi-Omics Dataset for MultiOmicsBridge
#'
#' @description
#' A small, self-contained simulated paired multi-omics dataset inspired by
#' inflammatory bowel disease (IBD) biology. This dataset is used throughout
#' package examples, tests, and the vignette to demonstrate the complete
#' MultiOmicsBridge analysis pipeline.
#'
#' @details
#' The dataset is a named list stored as an RDS file in
#' \code{inst/extdata/example_multiomics.rds}. It contains 30 samples
#' (15 ulcerative colitis [UC], 15 healthy controls) with paired host
#' transcriptomics (800 genes) and gut microbiome (60 taxa) measurements.
#'
#' \strong{Data provenance:} All data are computationally simulated (not
#' derived from real patient data). Host RNA-seq counts are drawn from a
#' negative binomial distribution (\code{rnbinom(mu=180, size=3)}) with
#' IBD-associated fold changes injected for 25 signal genes.
#' Microbiome counts are drawn from \code{rnbinom(mu=600, size=2)} with
#' dysbiosis fold changes for 15 signal taxa. A deliberate cross-omics
#' correlation between CXCL8 (host) and Ruminococcus_gnavus (microbiome)
#' is injected to test biomarker network recovery.
#' The random seed is \code{set.seed(2026L)}.
#'
#' \strong{List elements:}
#' \describe{
#'   \item{\code{host_se}}{A
#'     \code{\link[SummarizedExperiment]{SummarizedExperiment}}
#'     with 800 genes (rows) x 30 samples (columns). Contains raw counts
#'     and voom-normalized assays. Includes 15 IBD-upregulated genes
#'     (CXCL8, S100A8, IL6, TNF, etc.), 10 IBD-downregulated genes
#'     (MUC2, TFF3, etc.), and 775 neutral background genes.}
#'   \item{\code{mb_se}}{A
#'     \code{\link[SummarizedExperiment]{SummarizedExperiment}}
#'     with 60 taxa (rows) x 30 samples (columns). Contains raw counts
#'     and CLR-normalized assays. Includes 8 UC-enriched taxa
#'     (Ruminococcus_gnavus, Escherichia_coli, etc.), 7 UC-depleted taxa
#'     (Faecalibacterium_prausnitzii, Roseburia_intestinalis, etc.),
#'     and 45 neutral background taxa.}
#'   \item{\code{mae}}{A
#'     \code{\link[MultiAssayExperiment]{MultiAssayExperiment}}
#'     combining both omics layers with matched sample mappings.}
#'   \item{\code{outcome}}{A character vector of length 30 with values
#'     \code{"UC"} (first 15) and \code{"Control"} (last 15).}
#'   \item{\code{metadata}}{A \code{data.frame} with 30 rows and columns:
#'     \code{condition}, \code{age}, \code{sex}, \code{bmi},
#'     \code{disease_duration_yrs} (NA for controls).}
#'   \item{\code{ground_truth}}{A list containing known signal features
#'     for validation: \code{ibd_up_genes} (15 gene names),
#'     \code{ibd_down_genes} (10 gene names), \code{uc_up_taxa}
#'     (8 taxon names), \code{uc_down_taxa} (7 taxon names), and
#'     \code{correlated_pair} (CXCL8 and Ruminococcus_gnavus).}
#' }
#'
#'
#' @return A named list with 6 elements: \code{host_se}, \code{mb_se},
#'   \code{mae}, \code{outcome}, \code{metadata}, and \code{ground_truth}.
#'   See Details for full descriptions of each element.
#'
#' @format A named list with 6 elements. See Details.
#'
#' @source
#' Generated by \code{inst/scripts/make_example_data.R}. All data are
#' simulated; no real patient data is included.
#'
#' @seealso \code{\link{MultiOmicsBridgeAnalysis}},
#'   \code{\link{loadHostData}}, \code{\link{loadMicrobiomeData}},
#'   \code{\link{matchSamples}}
#'
#' @examples
#' ex <- readRDS(system.file("extdata", "example_multiomics.rds",
#'                            package = "MultiOmicsBridge"))
#' names(ex)
#' ex$mae
#' table(ex$outcome)
#' head(ex$metadata)
#'
#' @docType data
#' @name example_multiomics
#' @keywords datasets
NULL
